# .github/dependabot.yml
version: 2
updates:
  # 1. GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # 2. Node.js (npm / yarn / pnpm)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"