name: Continuous Integration
on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: my-astro-blog # Change the working directory, since npm doesn't really run from the root
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js Runtime
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: my-astro-blog/package-lock.json # Custom cache here, since all these eval steps will still run from the root even when working directory is listed above.

      - name: Install Project Dependencies
        run: npm ci

      - name: Run Static Analysis & Tests
        run: |
          npm run lint
          npm run check
          npm run test:unit